### PR TITLE
make job queue db aware #2

### PR DESCRIPTION
**Pull request by royalharsh**

### CODE REVIEW

**Comment by claudijd** [comment]
Is there a specific reason we cannot create a schema that supports the queue and results in the same table?

Crude Example (just for example sake):

target, uuid, status (queued, running, complete), results, error, etc.

I'm suggesting this because it makes DB querying, status, and metrics a one-stop-shop.

**Comment by royalharsh** [comment]
I haven't started working on it yet. I have just fixed the conflicts from @rishabhs95's pull request. I was also thinking to create a schema that supports the queue and results in the same table. I will fix this.

**Comment by claudijd** [comment]
FYI: I just killed the sqlite option for DB support, it's proving to be more of a burden than a help.  We're structured well to add more DBs in the future or swap them out, but for now I just want to maintain one DB tech to reduce overhead.

**Comment by claudijd** [comment]
Superceded by #58

**Pull request closed without merging**
